[package]
name = "semi_common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true, features = ["sync", "rt"] }
tracing = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
async-trait = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
